version: '3.8'
services:
  postgres-person-api:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=person_data
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db-init-scripts/postgres-person-api:/docker-entrypoint-initdb.d
  mongo-movie-api:
    image: mongo:4.2.24
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./db-init-scripts/mongodb-movie-api/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
volumes:
  postgres:
    driver: local
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local