FROM node:lts-alpine as BUILD
WORKDIR /usr/src/app
COPY package*.json ./
COPY .prod-env .env
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.25.0

COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /code
COPY --from=BUILD /usr/src/app/build .
EXPOSE 8080:8080
CMD ["nginx", "-g", "daemon off;"]