FROM nginx:1.25.0

ENV REACT_APP_PERSON_SERVICE_BASE_URL='http://localhost:8080'
ENV REACT_APP_PERSON_SERVICE_USER_KEY=''
ENV REACT_APP_MOVIE_SERVICE_BASE_URL='http://localhost:8081'
ENV REACT_APP_MOVIE_SERVICE_USER_KEY=''
ENV REACT_APP_MOVIE_TRACKING_SERVICE_BASE_URL='http://localhost:8082'
ENV REACT_APP_MOVIE_TRACKING_SERVICE_USER_KEY=''

RUN mkdir -p /var/cache/nginx
RUN mkdir -p /var/cache/nginx/scgi_temp
RUN mkdir -p /var/cache/nginx/uwsgi_temp
RUN mkdir -p /var/cache/nginx/proxy_temp
RUN mkdir -p /var/cache/nginx/client_temp
RUN mkdir -p /var/cache/nginx/fastcgi_temp
RUN chown nginx:nginx /var/cache/nginx

COPY ./build /usr/share/nginx/html/

USER nginx
EXPOSE 8080
CMD ["nginx","-g","daemon off;"]