apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: microservice-account-on-person-data-changed-in-memory-subscription
  namespace: 'maarten-playground'
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: abc
#  delivery: TODO enable
#    deadLetterSink:
#      ref:
#        apiVersion: serving.knative.dev/v1
#        kind: Service
#        name: error-handler
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-service-microservice-account
      namespace: 'maarten-playground'
