apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: microservice-account-on-address-data-changed-kafka-subscription
  namespace: <NAMESPACE>
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-address-data-changed-channel
#  delivery: TODO enable
#    deadLetterSink:
#      ref:
#        apiVersion: serving.knative.dev/v1
#        kind: Service
#        name: error-handler
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-service-microservice-account
      namespace: <NAMESPACE>
    uri: /api/accounts/data-change/address-data/via-channel
