apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kafka-native-broker-trigger-person-data
spec:
  broker: kafka-native-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-service-microservice-account
      namespace: <NAMESPACE>
    uri: /via-broker