apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kafka-native-broker-trigger-person-data
spec:
  broker: kafka-native-broker-person-data
#  filter:
#    expression: >
#      cd.data["birthDate"] == "ok"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-service-microservice-account
      namespace: voxxed-dry-run
    uri: /api/accounts/data-change/person-data/via-broker