apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: <NAMESPACE>
  name: knative-service-microservice-person
spec:
  template:
    spec:
      containers:
        - image: <DOCKER_IMAGE>
          ports:
            - containerPort: 8083